export const EngineConfig = {
  debug: {
    enabled: false,
    showVelocity: true,
    showBoundingBox: true,
    showContacts: true,
    showNormals: true,
    showGrid: false,
    showSleeping: true,
  },
  simulation: {
    fixedDt: 1 / 60,
    maxFrameDt: 0.1,
    maxStepsPerFrame: 5,
    paused: false,
    stepRequested: false,
    timeScale: 1,
  },
  physics: {
    solverIterations: 8,
    gravityX: 0,
    gravityY: 981,
    friction: 0.4,
    bounce: 0.5,
    linearDamping: 0.992,
    angularDamping: 0.985,
    sleepLinearThreshold: 2,
    sleepAngularThreshold: 0.05,
    sleepTimeThreshold: 0.5,
    dragStiffness: 42,
    dragDamping: 8,
  },
  world: {
    particleCount: 80,
    scene: "sandbox",
  },
};
